include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    BUNDLE: "iagno-dev.flatpak"

flatpak:
    variables:
        MANIFEST_PATH: "org.gnome.Reversi.json"
        FLATPAK_MODULE: "iagno"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.Reversi"
    extends: .flatpak

nightly:
    extends: '.publish_nightly'
    dependencies: ['flatpak']
    needs: ['flatpak']
